#!/bin/bash

# Deploy Edge Function to Supabase
echo "🚀 Deploying Edge Function to Supabase..."
echo ""
echo "📋 MANUAL STEPS REQUIRED:"
echo ""
echo "1. Install Supabase CLI if not already installed:"
echo "   brew install supabase/tap/supabase"
echo "   OR"
echo "   npm install -g supabase"
echo ""
echo "2. Login to Supabase:"
echo "   supabase login"
echo ""
echo "3. Link to your project:"
echo "   supabase link --project-ref mzqbheqosfjddmbytkzz"
echo ""
echo "4. Deploy the Edge Function:"
echo "   supabase functions deploy submit-contact --no-verify-jwt"
echo ""
echo "5. Test the function:"
echo "   supabase functions invoke submit-contact --body '{\"name\":\"Test\",\"phone\":\"555-1234\",\"location\":\"Test\",\"details\":\"Test\"}'"
echo ""
echo "The Edge Function will bypass RLS policies and allow contact form submissions to work!"