// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ksmehxxzhtjqilrmikxb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtzbWVoeHh6aHRqcWlscm1pa3hiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc2MDQ1MTMsImV4cCI6MjA2MzE4MDUxM30.c1OTGbLZI1kUi8PMGVPUO1kRv3S35MKdg8PZdVOsNxw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});